server:
  port: 8089

logging:
  level:
    root: warn
    ru: debug

spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    # localhost
    url: jdbc:postgresql://localhost:5432/rsp-game-db
    username: postgres
    password: postgres

  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.PostgreSQLDialect
        hbm2ddl:
          auto: validate
    defer-datasource-initialization: false
    open-in-view: false
  mandatory-file-encoding: UTF-8

telegram:
  bot:
    token: 6524265011:AAHs7hScYcMcswKdi6YXT5JvHSxeRgCc-NI
    name: ROCK_SCISSORS_PAPER_GAME_V2_bot
#    token: ${BOT_TOKEN:6662766853:AAEXDNKKTY6KQpqhrM8tIvH12HSegUM24zY}

kafka:
  producer:
    bootstrap-servers: localhost:9092
    key-serializer: org.apache.kafka.common.serialization.StringSerializer
    value-serializer: org.apache.kafka.common.serialization.StringSerializer